name: Notify Slack on File Changes

on:
  push:
    branches:
      - master 

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is available

      - name: Get changed files
        id: changed_files
        run: |
          FILES=$(git diff --name-only HEAD^ HEAD | tr '\n' ',' | sed 's/,$//')
          AUTHORS=$(git log --format='%an' HEAD^..HEAD | sort -u | tr '\n' ',' | sed 's/,$//')

          echo "FILES=$FILES" >> $GITHUB_ENV
          echo "AUTHORS=$AUTHORS" >> $GITHUB_ENV

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          MESSAGE="*📢 Changes in ${REPO} on branch ${BRANCH}*\n\n"
          MESSAGE+="*👤 Authors:* ${AUTHORS}\n\n"
          MESSAGE+="*📂 Changed Files:*\n$(echo ${FILES} | tr ',' '\n')"

          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$(echo "$MESSAGE" | jq -R -s '.')\"}" $SLACK_WEBHOOK_URL
