name: Notify Slack on File Changes

on:
  push:
    branches:
      - main  # Change this to your target branch

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch last two commits to compare changes

      - name: Get changed files
        id: changed_files
        run: |
          echo "FILES=$(git diff --name-only HEAD^ HEAD | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV
          echo "AUTHORS=$(git log --format='%an' HEAD^..HEAD | sort -u | jq -R -s -c 'split("\n")[:-1]')" >> $GITHUB_ENV

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          REPO: ${{ github.repository }}
          BRANCH: ${{ github.ref_name }}
        run: |
          MESSAGE=":memo: *Changes in ${REPO} on branch ${BRANCH}* \n\n"
          MESSAGE+=":busts_in_silhouette: *Authors:* $(echo $AUTHORS | jq -r '. | join(", ")')\n\n"
          MESSAGE+=":file_folder: *Changed Files:* \n$(echo $FILES | jq -r '. | join("\n")')"

          curl -X POST -H 'Content-type: application/json' --data "{\"text\": \"$MESSAGE\"}" $SLACK_WEBHOOK_URL
